In [1]:
import os
os.getcwd()

'C:\\Users\\suraj'

In [2]:
os.chdir('C:\\Users\\suraj\\Desktop\\DSP25')

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [5]:
df= pd.read_csv("horse.csv")

In [6]:
df.head()

surgery    age  hospital_number  rectal_temp  pulse  respiratory_rate  \
0      no  adult           530101         38.5   66.0              28.0   
1     yes  adult           534817         39.2   88.0              20.0   
2      no  adult           530334         38.3   40.0              24.0   
3     yes  young          5290409         39.1  164.0              84.0   
4      no  adult           530255         37.3  104.0              35.0   

  temp_of_extremities peripheral_pulse mucous_membrane capillary_refill_time  \
0                cool          reduced             NaN            more_3_sec   
1                 NaN              NaN   pale_cyanotic            less_3_sec   
2              normal           normal       pale_pink            less_3_sec   
3                cold           normal   dark_cyanotic            more_3_sec   
4                 NaN              NaN   dark_cyanotic            more_3_sec   

   ... packed_cell_volume total_protein abdomo_appearance abdomo_protein  \
0  ...               45.0           8.4               NaN            NaN   
1  ...               50.0          85.0            cloudy            2.0   
2  ...               33.0           6.7               NaN            NaN   
3  ...               48.0           7.2     serosanguious            5.3   
4  ...               74.0           7.4               NaN            NaN   

      outcome  surgical_lesion lesion_1 lesion_2  lesion_3  cp_data  
0        died               no    11300        0         0       no  
1  euthanized               no     2208        0         0       no  
2       lived               no        0        0         0      yes  
3        died              yes     2208        0         0      yes  
4        died               no     4300        0         0       no  

[5 rows x 28 columns]

In [8]:
df.columns

Index(['surgery', 'age', 'hospital_number', 'rectal_temp', 'pulse',
       'respiratory_rate', 'temp_of_extremities', 'peripheral_pulse',
       'mucous_membrane', 'capillary_refill_time', 'pain', 'peristalsis',
       'abdominal_distention', 'nasogastric_tube', 'nasogastric_reflux',
       'nasogastric_reflux_ph', 'rectal_exam_feces', 'abdomen',
       'packed_cell_volume', 'total_protein', 'abdomo_appearance',
       'abdomo_protein', 'outcome', 'surgical_lesion', 'lesion_1', 'lesion_2',
       'lesion_3', 'cp_data'],
      dtype='object')

In [9]:
target = df['outcome']

In [10]:
target.head()

0          died
1    euthanized
2         lived
3          died
4          died
Name: outcome, dtype: object

In [11]:
target.unique()

array(['died', 'euthanized', 'lived'], dtype=object)

In [13]:
len(target)

299

In [14]:
len(df)

299

In [15]:
df=df.drop(['outcome'], axis=1)

In [16]:
## Creating Dummy variables

categorical_variable = ['surgery', 'age', 'temp_of_extremities', 'peripheral_pulse',
       'mucous_membrane', 'capillary_refill_time', 'pain', 'peristalsis',
       'abdominal_distention', 'nasogastric_tube', 'nasogastric_reflux', 'rectal_exam_feces', 'abdomen','abdomo_appearance',
       'surgical_lesion', 'cp_data']
                        
                        
for category in categorical_variable:
    df[category]= pd.get_dummies(df[category])
                        

In [17]:
df.head()

surgery  age  hospital_number  rectal_temp  pulse  respiratory_rate  \
0        1    1           530101         38.5   66.0              28.0   
1        0    1           534817         39.2   88.0              20.0   
2        1    1           530334         38.3   40.0              24.0   
3        0    0          5290409         39.1  164.0              84.0   
4        1    1           530255         37.3  104.0              35.0   

   temp_of_extremities  peripheral_pulse  mucous_membrane  \
0                    0                 0                0   
1                    0                 0                0   
2                    0                 0                0   
3                    1                 0                0   
4                    0                 0                0   

   capillary_refill_time  ...  abdomen  packed_cell_volume  total_protein  \
0                      0  ...        1                45.0            8.4   
1                      0  ...        0                50.0           85.0   
2                      0  ...        0                33.0            6.7   
3                      0  ...        0                48.0            7.2   
4                      0  ...        0                74.0            7.4   

   abdomo_appearance  abdomo_protein  surgical_lesion  lesion_1  lesion_2  \
0                  0             NaN                1     11300         0   
1                  0             2.0                1      2208         0   
2                  0             NaN                1         0         0   
3                  0             5.3                0      2208         0   
4                  0             NaN                1      4300         0   

   lesion_3  cp_data  
0         0        1  
1         0        1  
2         0        0  
3         0        0  
4         0        1  

[5 rows x 27 columns]

In [18]:
from sklearn.model_selection import train_test_split

## for target variable to convert into numbers

from sklearn.preprocessing import LabelEncoder

In [19]:
X,y = df.values, target.values

In [20]:
X

array([[1.00000e+00, 1.00000e+00, 5.30101e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [0.00000e+00, 1.00000e+00, 5.34817e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.30334e+05, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       ...,
       [0.00000e+00, 1.00000e+00, 5.29386e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [0.00000e+00, 1.00000e+00, 5.30612e+05, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [0.00000e+00, 1.00000e+00, 5.34618e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00]])

In [21]:
y

array(['died', 'euthanized', 'lived', 'died', 'died', 'lived', 'lived',
       'died', 'euthanized', 'lived', 'lived', 'lived', 'lived', 'died',
       'lived', 'died', 'died', 'lived', 'lived', 'lived', 'lived',
       'lived', 'lived', 'lived', 'lived', 'lived', 'lived', 'lived',
       'died', 'lived', 'died', 'euthanized', 'lived', 'lived', 'lived',
       'euthanized', 'euthanized', 'lived', 'lived', 'died', 'died',
       'lived', 'lived', 'euthanized', 'euthanized', 'died', 'lived',
       'lived', 'died', 'died', 'lived', 'died', 'lived', 'lived',
       'euthanized', 'died', 'lived', 'died', 'died', 'died', 'lived',
       'lived', 'died', 'euthanized', 'lived', 'lived', 'lived', 'lived',
       'lived', 'lived', 'euthanized', 'lived', 'died', 'died', 'died',
       'euthanized', 'lived', 'lived', 'died', 'lived', 'died', 'lived',
       'lived', 'died', 'lived', 'lived', 'died', 'euthanized', 'lived',
       'lived', 'lived', 'died', 'lived', 'died', 'lived', 'lived',
       

In [23]:
label_encod= LabelEncoder()
y= label_encod.fit_transform(y)

In [24]:
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size= 0.3, random_state=100)

In [25]:
y

array([0, 1, 2, 0, 0, 2, 2, 0, 1, 2, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 0, 1, 2, 2, 2, 1, 1, 2, 2, 0, 0, 2, 2, 1,
       1, 0, 2, 2, 0, 0, 2, 0, 2, 2, 1, 0, 2, 0, 0, 0, 2, 2, 0, 1, 2, 2,
       2, 2, 2, 2, 1, 2, 0, 0, 0, 1, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 1,
       2, 2, 2, 0, 2, 0, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 1, 0,
       0, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 1, 2, 0, 1, 2, 2, 2, 1, 2, 0, 0,
       2, 0, 0, 0, 2, 2, 2, 2, 0, 0, 2, 1, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 1, 2, 2, 2, 0, 2, 1, 2, 1, 2, 2, 2, 1, 2, 0, 2, 0, 0, 2, 2,
       0, 2, 1, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 0, 2,
       2, 2, 0, 1, 2, 2, 1, 2, 0, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 0, 2, 1, 2, 2, 0, 2, 2, 2, 0, 2, 2, 1, 1, 0, 2, 0,
       2, 2, 0, 2, 0, 2, 2, 1, 0, 0, 2, 2, 0, 1, 0, 2, 0, 2, 2, 2, 0, 2,
       1, 2, 2, 2, 2, 0, 2, 2, 0, 1, 0, 1, 2, 2, 2, 2, 0, 0, 2, 2, 2, 1,
       2, 2, 2, 2, 0, 0, 1, 2, 1, 1, 0, 2, 1])

In [26]:
## missing value treatment

from sklearn.preprocessing import Imputer
imputer= Imputer(missing_values= 'NaN', strategy = "most_frequent", axis = 0)
X_train = imputer.fit_transform(X_train)
X_test = imputer.fit_transform(X_test)

C:\Users\suraj\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [30]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train,y_train)



DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [31]:
y_predict= classifier.predict(X_test)
y_predict

array([2, 2, 2, 1, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 0, 0, 2, 0, 2, 2, 0, 1, 2, 0, 1, 0, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 1, 1, 0, 0, 0, 0, 2, 2, 1, 1, 0, 2, 2, 2,
       2, 1, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 1,
       2, 0])

In [32]:
y_test

array([2, 2, 2, 2, 0, 0, 1, 2, 2, 1, 2, 0, 2, 2, 2, 2, 0, 1, 2, 0, 2, 2,
       2, 2, 0, 1, 2, 2, 2, 1, 2, 1, 0, 2, 2, 2, 2, 0, 2, 2, 1, 0, 2, 1,
       2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 1, 2, 2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 0])

In [33]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_predict)
accuracy

0.6666666666666666

In [39]:
from sklearn.ensemble import RandomForestClassifier 
classifier1 = RandomForestClassifier(n_estimators =500, criterion = 'entropy')
classifier1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [40]:
y_pred= classifier1.predict(X_test)
y_pred

array([0, 2, 2, 2, 0, 0, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2,
       2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 1, 2, 2, 1,
       2, 0])

In [42]:
accuracy1= accuracy_score(y_test,y_pred)
accuracy1

0.7666666666666667

In [43]:
from sklearn.ensemble import BaggingClassifier
claass= BaggingClassifier(n_estimators =500, max_samples = 0.1)
claass.fit(X_train,y_train)

BaggingClassifier(base_estimator=None, bootstrap=True, bootstrap_features=False,
                  max_features=1.0, max_samples=0.1, n_estimators=500,
                  n_jobs=None, oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [44]:
y_pred= claass.predict(X_test)
y_pred

array([0, 2, 2, 2, 0, 0, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2,
       2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0])

In [45]:
accuracy1= accuracy_score(y_test,y_pred)
accuracy1

0.7888888888888889